### ISSUE TITLE
Results task

### ISSUE THREAD

**Issue by arnaudbore** [UNFmontreal/toad#111]
Here is a list of files that we need to add a link to refere to in the results folder:

dwi_   -> upsampe/dwi_upsample.nii.gz
b       ->       ../03-eddy/dwi_EN464_subset_eddy.b
bvec       ->       ../03-eddy/dwi_subset_eddy.bvec
bval       ->       ../03-eddy/dwi_subset_eddy.bval
anat_   ->  register/anat_freesurfer_resample.nii.gz
brain_mask -> register/brain_mask_resample.nii.gz
brodmann -> register/brodman_resample.nii.gz

fa_dipy, ad_dipy, rd_dipy, md_dipy, nufo_dipy, gfa_dipy, rgb -> tensordipy
fa_fsl, ad_fsl, rd_fsl, md_fsl -> tensorfsl
fa_mrtrix, ad_mrtrix, rd_mrtrix, md_mrtrix -> tensormrtrix

Any suggestions about the name of these links ?

We can use subjectname_* : (ex S01)

S01_anat.nii.gz
S01_dwi.nii.gz
S01_brain_mask.nii.gz
S01_dipy_fa.nii.gz

**Comment by mathieudesro** [comment]
Done
