### ISSUE TITLE
[QA] New QA session about software version

### ISSUE THREAD

**Issue by arnaudbore** [UNFmontreal/toad#132]
As discussed during the TOAD meeting we should add a new QA session where information about the different softwares version used during the pipeline. We should add also a summary of the analysis.

Christophe if you need help don't hesitate !

**Comment by arnaudbore** [comment]
We need also:
RGB (Dipy)
Tensor (Dipy)

**Comment by cbedetti** [comment]
Software versioning shows in the qa.
#219
