### ISSUE TITLE
Warning message in tractography QA

### ISSUE THREAD

**Issue by arnaudbore** [UNFmontreal/toad#155]
Because we don't have unlimited storage we should add a warning message in the QA so the user know that we donwsampled the streamlines.

---
Warning:  due to storage restriction streamlines were downsampled. Even if there is no difference in structural connectivity you should be carefull if you want to compute metrics along streamlines.
---

Maybe we should provide the command line or tell them wich option they should change if they want to remove downsampling.

**Comment by mathieudesro** [comment]
Done

**Comment by cbedetti** [comment]
Resolved with #167
