### ISSUE TITLE
NLMEANS 32 coils channel - Error message

### ISSUE THREAD

**Issue by arnaudbore** [UNFmontreal/toad#156]
We've got some issue to estimate noise when we've got images from 32 coils channel.
PIESNO and estimate_sigma from dipy won't work so we need to tell user that we won't be able to run NLMEANS on 32 coils channel images at the beginning of the pipeline.

They need to change their denoising method to LPCA or None for the moment.

**Comment by mathieudesro** [comment]
Have we test if connecting only the upper part or the lower part of the coil raise the same issues???

We should investigated furthers why the 32 head coil is problematic???

**Comment by mathieudesro** [comment]
Done
