### ISSUE TITLE
Freesurfer GPU acceleration

### ISSUE THREAD

**Issue by arnaudbore** [UNFmontreal/toad#161]
To improve the speed of our pipeline we should think about the GPU implementation of Freesurfer so we can get faster. I know that @bpinsard set up it on his computer and it works pretty well.

What do you think about it ?

**Comment by mathieudesro** [comment]
Need to Install a NVIDIA video card and install  the cuds library.

**Comment by bpinsard** [comment]
there is a nvidia card (GeForce GT 640 Rev. 2) already on stark if I'm
right?
The only problem is when we have multiple GPU for dispatch which has to be
done by setting environment variable.

On Fri, Sep 25, 2015 at 2:26 PM, Mathieu Desrosiers <
notifications@github.com> wrote:

> Need to Install a NVIDIA video card and install the cuds library.
>
>
>
> Le 2015-09-25 à 14:21, arnaudbore <notifications@github.com> a écrit :
>
> > To improve the speed of our pipeline we should think about the GPU
> implementation of Freesurfer so we can get faster. I know that @bpinsard
> set up it on his computer and it works pretty well.
> >
> > What do you think about it ?
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UNFmontreal/toad/issues/161#issuecomment-143314823>.
>



-- 
Basile Pinsard

*PhD candidate, *
Laboratoire d'Imagerie Biomédicale, UMR S 1146 / UMR 7371, Sorbonne
Universités, UPMC, INSERM, CNRS
*Brain-Cognition-Behaviour Doctoral School **, *ED3C*, *UPMC, Sorbonne
Universités
Biomedical Sciences Doctoral School, Faculty of Medicine, Université de
Montréal
CRIUGM, Université de Montréal

**Comment by mathieudesro** [comment]
Bingo,

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GT 750M OpenGL Engine
OpenGL version string: 1.4 (2.1 NVIDIA-8.26.29 310.40.55f01)
OpenGL extensions:

Only need to install cuda

**Comment by bpinsard** [comment]
yes but you have to choose cuda5 not the latest(7), it is the only
compatible with freesurfer.

On Fri, Sep 25, 2015 at 4:41 PM, Mathieu Desrosiers <
notifications@github.com> wrote:

> Bingo,
>
> OpenGL vendor string: NVIDIA Corporation
> OpenGL renderer string: NVIDIA GeForce GT 750M OpenGL Engine
> OpenGL version string: 1.4 (2.1 NVIDIA-8.26.29 310.40.55f01)
> OpenGL extensions:
>
> Only need to install cuda
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UNFmontreal/toad/issues/161#issuecomment-143348428>.
>



-- 
Basile Pinsard

*PhD candidate, *
Laboratoire d'Imagerie Biomédicale, UMR S 1146 / UMR 7371, Sorbonne
Universités, UPMC, INSERM, CNRS
*Brain-Cognition-Behaviour Doctoral School **, *ED3C*, *UPMC, Sorbonne
Universités
Biomedical Sciences Doctoral School, Faculty of Medicine, Université de
Montréal
CRIUGM, Université de Montréal

**Comment by mathieudesro** [comment]
Stark now support both cuda-7.5 and cuda-5.0 (defaults 5.0).  
 
However,  Cuda 5.0 do a really poor job managing memory overflow and probably will failed each time 2 or more users launch cuda process.

Cuda will not be implemented into TOAD.
