### ISSUE TITLE
Bug -- Export freesurfer home in user bash profile

### ISSUE THREAD

**Issue by larlequin** [UNFmontreal/toad#215]
Toad will crash at the parcellation step if user has defined a Freesurfer_home with a final "/" in his/her .bash_profile:
- export FREESURFER_HOME='/usr/local/freesurfer/' -- **CRASHING**
- export FREESURFER_HOME='/usr/local/freesurfer' -- **WORKING**

**Comment by cbedetti** [comment]
Salut,

Il vaut mieux sourcer directement `unf-toad-config.sh` dans `.bash_profile`.
```
source /usr/local/toad/etc/unf-toad-config.sh
```
Ça devrait résoudre le crash.

**Comment by larlequin** [comment]
Salut, 

En je source également toad dans le bash_profile. Le fichier avait été créé par Mathieu avant les versions "moderne" de TOAD. Je le signal comme bug, car avec Arnaud, nous pensons que Toad devrait ignorer la définition du home de freesurfer de l’usager.

**Comment by cbedetti** [comment]
Je viens de faire un test avec un `.bash_profile` comme ça :
```
export FREESURFER_HOME='/usr/local/freesurfer/'
source /usr/local/toad/etc/unf-toad-config.sh
```
Ça me donne bien :
```
echo $FREESURFER_HOME
/usr/local/freesurfer
```
Faudra regarder le `.bash_profile` de l'utilisateur.

**Comment by larlequin** [comment]
J’ai fait quelques tests aussi. Il s’agit de savoir qui est défini en dernier. Si c’est toad, ça marche, si c’est l’export manuel, ça ne marche pas.

**Comment by arnaudbore** [comment]
Ce bug n'est plus d'actualité puisque nous utilisons maintenant aux modules.
