### ISSUE TITLE
unf2toad enhancement

### ISSUE THREAD

**Issue by arnaudbore** [UNFmontreal/toad#40]
- We should suggest a serie of DICOM for conversion.
- We should check the serie of DICOM to make sure that it makes sense for conversion.
- Once you've done the first subject we can ask if it's possible to repeat the same pattern of conversion for subjects that have the same series of DICOM.
- We should save list of converted subjects

**Comment by arnaudbore** [comment]
We definitively need to save the status of conversion (with stars).

**Comment by mathieudesro** [comment]
done
