### ISSUE TITLE
crash into hardidipy

### ISSUE THREAD

**Issue by mathieudesro** [UNFmontreal/toad#87]
INFO: Launching implementation of hardidipy task
INFO: Creating /scratch/bore_cardio/toad_data/HC_RC35_2/13-hardidipy directory
INFO: Starting tensors creation from dipy on /scratch/bore_cardio/toad_data/HC_RC35_2/05-preprocessing/dwi_HC_RC35_2_subset_eddy_unwarp_denoise_upsample.nii.gz
INFO: Start fODF computation

/usr/lib64/python2.7/site-packages/dipy/reconst/peaks.py:503: RuntimeWarning: invalid value encountered in double_scalars
  return np.sqrt(numer / denom)
/usr/lib64/python2.7/site-packages/dipy/reconst/peaks.py:503: RuntimeWarning: invalid value encountered in double_scalars
  return np.sqrt(numer / denom)
/usr/lib64/python2.7/site-packages/dipy/reconst/peaks.py:503: RuntimeWarning: invalid value encountered in double_scalars
  return np.sqrt(numer / denom)
/usr/lib64/python2.7/site-packages/dipy/reconst/peaks.py:503: RuntimeWarning: invalid value encountered in double_scalars
  return np.sqrt(numer / denom)
/usr/lib64/python2.7/site-packages/dipy/reconst/peaks.py:503: RuntimeWarning: invalid value encountered in double_scalars
  return np.sqrt(numer / denom)
/usr/lib64/python2.7/site-packages/dipy/reconst/csdeconv.py:576: UserWarning: maximum number of iterations exceeded - failed to converge
  warnings.warn(msg)
/opt/sge/default/spool/stark/job_scripts/18931: line 1:  5375 Bus error               (core dumped) /usr/local/toad//bin/toad /scratch/bore_cardio/toad_data/HC_RC35_2 -l -p

**Comment by mathieudesro** [comment]
We need to reimplement this task ASAP

**Comment by arnaudbore** [comment]
Never seen this since 27 august 2015. Issue closed.
