### ISSUE TITLE
masking in denoising

### ISSUE THREAD

**Issue by bpinsard** [UNFmontreal/toad#96]
masking in nlmeans denoising step causes zero stripes in denoised data.
dwi mask should be warped from anatomical image as in fieldmap step.

**Comment by mathieudesro** [comment]
Please confirm that this issue have been fix by the request #100

**Comment by bpinsard** [comment]
cannot confirm if is has been fixed, I do not run any dataset with Toad at that time.

**Comment by mathieudesro** [comment]
We found an alternative solution
Now piesno algorithm is use to estimate sigma
