### ISSUE TITLE
Magnitude registration

### ISSUE THREAD

**Issue by arnaudbore** [UNFmontreal/toad#99]
Some subjects fail to be well registered with anat. We should find a way to check if the registration went well and change parameters in case of "error".

1- Check registration
2- Add -usesqform in registration of magnitude, use norm.mgz instead of "anat freesurfer"

ASAP ;)

PS: What need to be modified:
-----> INFO: Coregistring magnitude image with the anatomical image produce by freesurfer

**Comment by mathieudesro** [comment]
fix
